### ISSUE TITLE
Game not recognized

### ISSUE THREAD

**Issue by IvanMazzoli** [Bidziilla/nxGTA-Trainers#5]
I've started GTA: SA on my Switch but the module reports "ERROR: TitleID Mismatch"; but a sneak peek at the code and to Edison confirms it's the correct one.
I'm _guessing_ the problem lays into the bid_match() routine, but I can't understand what value is looking for into the game to confirm it's the right one.
Attached you can find the Edizon applet reporting the game info

![Album_20211123_235649_00 (1)](https://user-images.githubusercontent.com/7896815/143142851-63f51962-e51d-4526-8ef4-2600ebf75ad9.jpg)

**Comment by SGTjulio** [comment]
Where did you get the nsp or xci? From 
Cause to me it seems like the file is probably not complete

**Comment by IvanMazzoli** [comment]
I've got the NSZ from HBG, via Tinfoil. Strangely it doesn't warn me about missing files/dlc or so.
Could be that I'm not from the States and maybe there's a different release here in Europe?

**Comment by j1nior** [comment]
same here, probably because the new update 1.0.3 released... (it was working before that)
maybe the dev needs to update for this release.
thanks in advance

**Comment by IvanMazzoli** [comment]
As far as I know I'm still playing on day-one release, I'll check asap and let you know the installed version.
I'm also trying to compile a version without the bid_match() routine to see if it still works or it breaks something, but I've got no clue how to compile homebrews for the Switch

**Comment by j1nior** [comment]
> As far as I know I'm still playing on day-one release, I'll check asap and let you know the installed version. I'm also trying to compile a version without the bid_match() routine to see if it still works or it breaks something, but I've got no clue how to compile homebrews for the Switch

Update to 1.0.2, but not 1.0.3, and test it... it should work (if I right)

**Comment by IvanMazzoli** [comment]
> Update to 1.0.2, but not 1.0.3, and test it... it should work (if I´m right)
No updates on the hbg shop, I must search somewhere else

**Comment by Bidziilla** [comment]
It doesn't support 1.0.3 yet, but that's being worked on right now.

**Comment by IvanMazzoli** [comment]
I confirm I'm on 1.0.0 and doesn't work. I'll try to update to 1.0.2 and see if works

**Comment by Bidziilla** [comment]
> I confirm I'm on 1.0.0 and doesn't work. I'll try to update to 1.0.2 and see if works

Yes, it only works for 1.0.2 because it was what came with the game on launch when I installed it.
Please stay tuned for the update for 1.0.3!!
